In [1]:
import numpy as np
import pandas as pd
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from datetime import datetime

In [4]:
client = CryptoHistoricalDataClient()

In [14]:
request_params = CryptoBarsRequest(
    symbol_or_symbols=["BTC/USD"],
    timeframe=TimeFrame.Minute,
    start=datetime(2022, 7, 1),
    end=datetime(2024, 7, 1)
)

In [15]:
bars = client.get_crypto_bars(request_params)

In [16]:
df = bars.df
df.index = df.index.droplevel(0)

In [17]:
df

,open,high,low,close,volume,trade_count,vwap
timestamp,,,,,,,
2022-07-01 00:00:00+00:00,19935.5300,19957.1700,19786.4600,19811.0100,20.574674,329.0,19907.190021
2022-07-01 00:01:00+00:00,19785.9200,19828.7900,19753.6800,19806.4000,16.330260,272.0,19782.719056
2022-07-01 00:02:00+00:00,19812.2300,19853.6800,19731.8800,19737.5700,10.453886,213.0,19783.945951
2022-07-01 00:03:00+00:00,19729.8900,19777.3900,19719.0000,19727.9600,10.916530,202.0,19739.097710
2022-07-01 00:04:00+00:00,19719.0600,19729.8200,19662.9900,19681.2400,14.034318,256.0,19695.750629
...,...,...,...,...,...,...,...
2024-06-30 23:52:00+00:00,62741.6800,62741.6800,62741.6800,62741.6800,0.000000,0.0,0.000000
2024-06-30 23:53:00+00:00,62769.1410,62769.1410,62769.1410,62769.1410,0.000000,0.0,0.000000
2024-06-30 23:54:00+00:00,62741.4430,62741.4430,62741.4430,62741.4430,0.000000,0.0,0.000000
2024-06-30 23:56:00+00:00,62768.1460,62768.1460,62733.0415,62733.0415,0.000000,0.0,0.000000
2024-06-30 23:59:00+00:00,62669.7615,62669.7615,62669.7615,62669.7615,0.000000,0.0,0.000000

In [18]:
df.to_csv("BTCUSD_M1.csv")